import type { Project } from "@/content/types";

export const projects = [
  {
    slug: "oneauto",
    name: "OneAuto",
    internalName: "Hbu_Onsite_Tasco",
    period: { start: "2026-01", end: "present" },
    company: "HBLAB JSC",
    client: "TASCO Group",
    role: "Frontend Developer",
    participation: "contributor",
    domain: "Automotive services",
    summary: "Workshop operations for automotive services in the TASCO ecosystem.",
    challenge:
      "Repair, accessory-sales, and roadside-assistance workflows need to remain clear while operators work with customer and vehicle data.",
    contribution:
      "Analyzed requirements, designed flows, built the frontend, integrated APIs, and handled validation, permissions, and testing.",
    responsibilities: [
      "Built repair-order, accessory-sales, and roadside-assistance workflows.",
      "Worked with business analysts to turn operational requirements into usable flows.",
      "Integrated APIs and implemented validation, permissions, and frontend testing.",
    ],
    highlights: [
      "Proposed and delivered an in-context drawer for creating or updating customer and vehicle-owner information without leaving the order flow.",
    ],
    technologies: ["Vue 3", "TypeScript", "Vue Router", "Ant Design Vue"],
    featured: true,
    ongoing: true,
    detail: {
      context: "A full-time HBLAB onsite engagement at TASCO Group.",
      technicalDecisions: [
        "Kept customer updates inside the active order screen to reduce context switching.",
      ],
    },
  },
  {
    slug: "property",
    name: "Property",
    internalName: "HB3_1677_Property",
    period: { start: "2025-04", end: "present" },
    company: "HBLAB JSC",
    client: "Auto Magic",
    role: "Frontend Developer",
    participation: "contributor",
    domain: "Property finance",
    summary: "A modern rebuild of a legacy building-accounting and financial-information system.",
    challenge:
      "The legacy UI, codebase, and documentation were no longer suitable for continued product development.",
    contribution:
      "Rebuilt the UI, investigated legacy behavior and APIs, and helped the BA recover business rules from the old system.",
    responsibilities: [
      "Reconstructed legacy behavior with the BA when documentation was incomplete or outdated.",
      "Built the new interface and integrated the available APIs.",
    ],
    highlights: ["Delivered a clearer UI on a more maintainable modern frontend foundation."],
    technologies: ["Next.js", "Ant Design"],
    featured: true,
    ongoing: true,
    detail: {
      context: "A replacement for a legacy system handling building accounting and financial data.",
    },
  },
  {
    slug: "hp-booster",
    name: "HP Booster",
    internalName: "HB3_1571_SWIPLE_System",
    period: { start: "2024-12", end: "2026-06" },
    company: "HBLAB JSC",
    client: "Tryhatch",
    role: "Frontend Sub-lead",
    participation: "lead",
    team: "Led 3 frontend developers",
    domain: "Marketing platform",
    summary: "A drag-and-drop marketing website builder migrated from React to Next.js.",
    challenge:
      "The original React SPA did not fit the product's SEO needs or its growing delivery scale.",
    contribution:
      "Reassessed the frontend foundation, planned the migration, implemented core changes, and coordinated three frontend developers.",
    responsibilities: [
      "Planned and implemented the React-to-Next.js migration.",
      "Broke work into tasks and coordinated three frontend developers.",
      "Resolved migration issues while preserving the existing builder behavior.",
    ],
    highlights: [
      "Improved SEO readiness and maintainability while moving the product to a framework better suited to its scale.",
    ],
    technologies: ["React", "Next.js", "SEO"],
    featured: true,
    detail: {
      context: "A visual marketing-site builder centered on drag-and-drop page creation.",
      technicalDecisions: ["Moved from a client-only React foundation to Next.js for SEO and maintainability."],
    },
  },
  {
    slug: "commerce-convert",
    name: "Commerce Convert",
    internalName: "HBU_1916_Commerce_NextJS",
    period: { start: "2026-03", end: "2026-05" },
    company: "HBLAB JSC",
    client: "Auto Magic",
    role: "Frontend Lead",
    participation: "lead",
    team: "2 frontend developers · 50% contribution",
    domain: "SEO modernization",
    summary: "React-to-Next.js migration for SEO and framework consistency.",
    challenge: "The application needed stronger SEO support and a shared framework across the client ecosystem.",
    contribution:
      "Reviewed and selected libraries, set the migration direction, guided the second developer, and reviewed the converted code.",
    responsibilities: [
      "Evaluated libraries and migration compatibility.",
      "Guided the implementation and reviewed the converted code.",
    ],
    highlights: ["Standardized the product on Next.js while improving its SEO foundation."],
    technologies: ["React", "Next.js", "SEO"],
    featured: false,
  },
  {
    slug: "kpro",
    name: "KPro",
    internalName: "HB3_1044_KPro",
    period: { start: "2023-04", end: "2026-01" },
    company: "HBLAB JSC",
    client: "Auto Magic",
    role: "Frontend Developer → Frontend Lead",
    participation: "lead",
    team: "Frontend team grew from 3 to 4 people",
    domain: "File management",
    summary: "A file-management product with deep hierarchical navigation.",
    challenge: "The file tree contains a large number of nodes and deeply nested levels.",
    contribution:
      "Progressed from developer to frontend lead, designed UI/UX and technical solutions, split tasks, and reviewed code.",
    responsibilities: [
      "Built file upload and file-list experiences.",
      "Designed and implemented the left-side hierarchical tree navigation.",
      "Supported solution design, task breakdown, UI/UX, and code review as frontend lead.",
    ],
    highlights: [
      "Implemented infinite loading for a large, deeply nested tree to reduce upfront data work and improve interface performance.",
    ],
    technologies: ["Next.js", "Ant Design"],
    featured: true,
    detail: {
      context: "A long-running file-management engagement for Auto Magic.",
      technicalDecisions: ["Loaded a deep tree incrementally instead of rendering every node up front."],
    },
  },
  {
    slug: "grafana-tools",
    name: "Grafana Tools",
    internalName: "HB4_1453_Yokogawa",
    period: { start: "2024-12", end: "2026-01" },
    company: "HBLAB JSC",
    client: "Yokogawa Digital Corporation",
    role: "Frontend Developer",
    participation: "contributor",
    domain: "Observability tooling",
    summary: "Reimplementation of customer-specific Grafana customizations on a Grafana 12.2 foundation.",
    challenge:
      "The customer's product had been customized from Grafana 6.3.4 and needed its behavior carried to a much newer Grafana base.",
    contribution:
      "Located equivalent behavior in official Grafana source, researched the implementation, planned the customization, and coded it in React.",
    responsibilities: [
      "Compared customer behavior with the official Grafana implementation.",
      "Planned and implemented React customizations for data retrieval and display.",
    ],
    highlights: ["Recreated customer-specific behavior without presenting the work as a simple version upgrade."],
    technologies: ["React", "Grafana 12.2"],
    featured: false,
  },
  {
    slug: "workflow",
    name: "Workflow",
    internalName: "HB3_1241_Workflow",
    period: { start: "2024-02", end: "2025-06" },
    company: "HBLAB JSC",
    client: "Auto Magic",
    role: "Frontend Lead",
    participation: "lead",
    team: "4 FE · 3 BE · 2 QA · 1 PM · 1 Comtor/BA",
    domain: "Workflow management",
    summary: "An internal system for defining workflows, assigning tasks, and tracking progress.",
    challenge: "Users needed to create their own workflow or start from approved master data.",
    contribution: "Analyzed requirements with the Comtor/BA, split frontend tasks, and built workflow creation.",
    responsibilities: [
      "Built the workflow-creation experience.",
      "Supported both custom workflows and reusable workflow master data.",
      "Analyzed requirements and divided work for the frontend team.",
    ],
    technologies: ["Next.js"],
    featured: false,
  },
  {
    slug: "pfd-maintain",
    name: "PFD Maintain",
    internalName: "HB3_1731_PFDMaintain",
    period: { start: "2025-06", end: "2025-06" },
    company: "HBLAB JSC",
    client: "Auto Magic",
    role: "Frontend Reviewer",
    participation: "reviewer",
    domain: "Document workflow",
    summary: "A short extension that added PDF upload and viewing to the KPro product context.",
    contribution: "Reviewed the proposed solution and implementation rather than building the feature directly.",
    responsibilities: ["Reviewed the PDF upload and viewing implementation."],
    technologies: [],
    featured: false,
  },
  {
    slug: "musa-pms",
    name: "MUSA PMS",
    internalName: "HB3_KP91_MUSA_PMS",
    period: { start: "2024-12", end: "2025-05" },
    company: "HBLAB JSC",
    client: "MUSA",
    role: "Frontend Lead",
    participation: "lead",
    team: "3 frontend developers",
    domain: "Workforce management",
    summary: "An admin product for work, attendance, leave, and employee scheduling.",
    challenge: "The Gantt timeline needed to match the customer's workforce-planning interface.",
    contribution: "Led estimation and frontend delivery, and customized the Gantt timeline UI.",
    responsibilities: [
      "Estimated and led frontend work for a three-person team.",
      "Customized the visual timeline in gantt-task-react.",
    ],
    highlights: ["The customer accepted the delivered interface."],
    technologies: ["React", "gantt-task-react"],
    featured: false,
  },
  {
    slug: "workorder",
    name: "WorkOrder",
    internalName: "HB3_1414_WorkOrder",
    period: { start: "2024-08", end: "2025-02" },
    company: "HBLAB JSC",
    client: "Auto Magic",
    role: "Frontend Lead",
    participation: "lead",
    domain: "Commercial workflow product",
    summary: "A commercial workflow builder configurable by multiple customer companies.",
    challenge: "The internal workflow concept needed to become a configurable product for different companies.",
    contribution: "Led frontend analysis, task breakdown, review, and the workflow-builder implementation.",
    responsibilities: [
      "Built the workflow builder.",
      "Analyzed requirements, split tasks, and reviewed frontend code.",
    ],
    technologies: ["Next.js"],
    featured: false,
  },
  {
    slug: "kotoba-stripe",
    name: "Kotoba Stripe",
    internalName: "HB3_1502_KLabo",
    period: { start: "2024-10", end: "2024-11" },
    company: "HBLAB JSC",
    client: "Kotoba",
    role: "Frontend Developer",
    participation: "contributor",
    domain: "Payments",
    summary: "A React payment experience combining multiple Stripe payment and account flows.",
    challenge: "Payment behavior and UI decisions had to be explained directly to a non-technical customer.",
    contribution: "Researched Stripe, proposed the payment UI, implemented the flows, and worked 1:1 with the customer in English.",
    responsibilities: [
      "Designed and implemented multiple Stripe payment flows in React.",
      "Translated technical constraints into decisions a non-technical customer could evaluate.",
    ],
    highlights: ["The customer accepted the completed payment experience and gave positive feedback."],
    technologies: ["React", "Stripe"],
    featured: false,
  },
  {
    slug: "commerce",
    name: "Commerce",
    internalName: "HB3_1059_Commerce",
    period: { start: "2023-08", end: "2024-06" },
    company: "HBLAB JSC",
    client: "Auto Magic",
    role: "Frontend Tech Lead",
    participation: "lead",
    team: "Led 3 frontend developers",
    domain: "Building management",
    summary: "Building management and financial workflows with Google Maps and Terra Map.",
    challenge:
      "Terra Map documentation was primarily Japanese and left important API behavior undocumented.",
    contribution:
      "Designed map API flows, built building visualization and detail views, divided tasks, reviewed code, and delivered formula settings in the admin product.",
    responsibilities: [
      "Displayed buildings and building details across Google Maps and Terra Map.",
      "Tested and inferred undocumented Terra Map behavior.",
      "Built formula settings with input/selection, format checks, and validation before save.",
      "Led solution design, task breakdown, and code review for three frontend developers.",
    ],
    highlights: ["Turned incomplete third-party documentation into a working map integration."],
    technologies: ["Next.js", "Google Maps", "Terra Map"],
    featured: true,
    detail: {
      context: "A building-management product with map and financial-administration workflows.",
      technicalDecisions: ["Validated formula structure and format before accepting configuration changes."],
    },
  },
  {
    slug: "account",
    name: "Account",
    company: "HBLAB JSC",
    client: "Auto Magic",
    role: "Frontend Lead",
    participation: "lead",
    domain: "Identity and access",
    summary: "Centralized user management and authorization for products including KPro.",
    challenge: "Multiple products needed a consistent way to manage access.",
    contribution: "Designed and integrated a User → Group → Role permission model.",
    responsibilities: [
      "Designed the frontend permission model around users, groups, and roles.",
      "Integrated the account experience with products in the Auto Magic ecosystem.",
    ],
    technologies: ["Next.js"],
    featured: false,
  },
  {
    slug: "viettel-family-registration",
    name: "Viettel Family — Competition Registration",
    company: "Viettel Software Service",
    role: "Mobile Developer",
    participation: "contributor",
    domain: "Internal registration workflow",
    summary: "An internal mobile registration flow for Viettel Family competition activities.",
    contribution: "Built the application flow and integrated the required APIs in React Native.",
    responsibilities: [
      "Implemented the competition-registration flow.",
      "Connected the mobile interface to application APIs.",
    ],
    highlights: ["Released for internal use at Viettel."],
    technologies: ["React Native", "REST APIs"],
    featured: false,
    confidential: true,
  },
  {
    slug: "aia-components",
    name: "AIA Components",
    company: "FPT Software",
    client: "AIA Thailand",
    role: "Frontend Developer",
    participation: "contributor",
    domain: "UI engineering",
    summary: "A reusable React component system structured with Atomic Design.",
    challenge: "Shared interface elements needed consistent implementation, documentation, and browser-level verification.",
    contribution: "Worked 1:1 in English with a Malaysian client representative and delivered documented, tested components.",
    responsibilities: [
      "Built reusable Button, Select, and infinite-scroll Select components.",
      "Documented component behavior in Storybook and verified it with Playwright.",
    ],
    highlights: ["The customer accepted the delivered component set."],
    technologies: ["React", "Storybook", "Playwright", "Atomic Design"],
    featured: true,
    detail: {
      context: "AIA Thailand component delivery with direct English-language client collaboration.",
      technicalDecisions: ["Organized reusable UI using Atomic Design."],
    },
  },
  {
    slug: "requirement-tool",
    name: "Requirement Tool",
    company: "FPT Software",
    role: "Frontend Developer",
    participation: "contributor",
    domain: "Enterprise requirements",
    summary: "A React authoring tool for business analysts to manage software requirements.",
    challenge: "The editor needed product-specific authoring behavior beyond the default rich-text experience.",
    contribution: "Implemented CKEditor logic for BA requirement authoring.",
    responsibilities: [
      "Customized CKEditor toolbar and plugins.",
      "Handled formatting, pasted content, requirement templates, and validation.",
    ],
    technologies: ["React", "CKEditor"],
    featured: false,
  },
] satisfies readonly Project[];

export const featuredProjects = projects.filter((project) => project.featured);

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug);
}

export function getAdjacentProjects(slug: string): { previous?: Project; next?: Project } {
  const index = projects.findIndex((project) => project.slug === slug);

  if (index < 0) {
    return {};
  }

  return {
    previous: projects[index - 1],
    next: projects[index + 1],
  };
}
